In [1]:
import numpy as np

In [2]:
# Numerical operations using Python lists
list_two = list(range(1, 4)) # 4 is exclusive
list_three = list(range(1, 4))
list_sum = []

print("Before: \n")
print(list_two)
print(list_three)

for index in range(3):
    list_two[index] = list_two[index] ** 2
    list_three[index] = list_three[index] ** 3
    list_sum.append(list_two[index] + list_three[index])

print("After: \n")
print(list_two)
print(list_three)
        
print(list_sum)

Before: 

[1, 2, 3]
[1, 2, 3]
After: 

[1, 4, 9]
[1, 8, 27]
[2, 12, 36]


In [3]:
# Numerical operations using Numpy array

array_two = np.arange(1, 4) ** 2
print(array_two)

[1 4 9]


In [4]:
array_three = np.arange(1, 4) ** 3
print(array_three)
print(array_two + array_three)

[ 1  8 27]
[ 2 12 36]


In [5]:
sample_array = np.array([1, 2, 3])

In [6]:
# Polynomial operations (power)
test_power = np.power(sample_array, 4)

In [7]:
print(test_power)

[ 1 16 81]


In [8]:
print(np.negative(sample_array))

[-1 -2 -3]


In [9]:
np.exp(sample_array)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [10]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229])

In [11]:
np.sin(sample_array)

array([0.84147098, 0.90929743, 0.14112001])

In [12]:
np.cos(sample_array)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [13]:
np.tan(sample_array)

array([ 1.55740772, -2.18503986, -0.14254654])

In [14]:
# Array arrangements
x = np.arange(3) # 1 row, 3 columns, numpy array value from 0 to 2 (3 is exclusive)
y = np.arange(3, 6) # All are 1-dimensional arrays
z = np.arange(3)

multi_array = np.array([x,y,z], dtype = np.int16)
print(multi_array)
print(multi_array.shape) # print array shape (3 r, 3 c)

# Indexing
multi_array[1, 2] # points to 1th row, 2nd column value (indexing starts from 0)

[[0 1 2]
 [3 4 5]
 [0 1 2]]
(3, 3)


5

In [15]:
w = np.linspace(1, 50, 100) # Gives out 50 rows of array, from evenly spaced no. from 1 to 10
print(w) # (value start, value end, n rows(step size))
print(w.shape)

[ 1.          1.49494949  1.98989899  2.48484848  2.97979798  3.47474747
  3.96969697  4.46464646  4.95959596  5.45454545  5.94949495  6.44444444
  6.93939394  7.43434343  7.92929293  8.42424242  8.91919192  9.41414141
  9.90909091 10.4040404  10.8989899  11.39393939 11.88888889 12.38383838
 12.87878788 13.37373737 13.86868687 14.36363636 14.85858586 15.35353535
 15.84848485 16.34343434 16.83838384 17.33333333 17.82828283 18.32323232
 18.81818182 19.31313131 19.80808081 20.3030303  20.7979798  21.29292929
 21.78787879 22.28282828 22.77777778 23.27272727 23.76767677 24.26262626
 24.75757576 25.25252525 25.74747475 26.24242424 26.73737374 27.23232323
 27.72727273 28.22222222 28.71717172 29.21212121 29.70707071 30.2020202
 30.6969697  31.19191919 31.68686869 32.18181818 32.67676768 33.17171717
 33.66666667 34.16161616 34.65656566 35.15151515 35.64646465 36.14141414
 36.63636364 37.13131313 37.62626263 38.12121212 38.61616162 39.11111111
 39.60606061 40.1010101  40.5959596  41.09090909 41.

In [16]:
b = np.linspace(1, 30)
b
print(b.shape)

(50,)


In [17]:
# 1-D array slicing
x = np.arange(1, 20)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [18]:
# Slicing from nth index to mth index, m exclusive
print(x[3:6]) # remember index always starts from 0
print(x[2:7:2]) # slice from 2th to 7th index, with a step size of 2
print(x[2:]) # slice from 2th to n-1th index, n = array size

[4 5 6]
[3 5 7]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [19]:
# N-dimensional array slicing, reshaping array
x = np.arange(9)
print(x)
print(x.shape)

[0 1 2 3 4 5 6 7 8]
(9,)


In [20]:
x = x.reshape(3, 3) # reshaping, must be compatible with the data, n = r*c
print(x)
print(x.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


In [21]:
z = np.arange(18).reshape(3, 3, 2) # reshape with n blocks of data, r rows, c columns
print(z)
print(z.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
(3, 3, 2)


In [22]:
print("\nslicing from [nth block, nth row, nth column]\n")
print(z[1, 1, 1]) # slicing from [nth block, nth row, nth column]
print("\nslicing from [nth block, ith to jth row, ith to jth column]\n")
print(z[1, 0:3, 0:2]) # slicing from [nth block, ith to jth row, ith to jth column]
print("\nassume slicing with all the elements in the nth block\n")
print(z[2, :, :]) # assume slicing with all the elements in the nth block
print("\nreplacing : with elipses (...)\n")
print(z[0, ...]) # replacing : with elipses (...)
print("\nslice 0th row and 0th col values of all blocks of data\n")
print(z[:, 0, 0]) # slice 0th row and 0th col values of all blocks of data
print("\n")
print(z[:, 0:3, 0:2]) 


slicing from [nth block, nth row, nth column]

9

slicing from [nth block, ith to jth row, ith to jth column]

[[ 6  7]
 [ 8  9]
 [10 11]]

assume slicing with all the elements in the nth block

[[12 13]
 [14 15]
 [16 17]]

replacing : with elipses (...)

[[0 1]
 [2 3]
 [4 5]]

slice 0th row and 0th col values of all blocks of data

[ 0  6 12]


[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]


In [23]:
# Slicing using boolean operation
comparison = z > 5
print(comparison)
print(z[comparison]) # or can do with (z[z>5])
print(z.max())
print(z.min())

[[[False False]
  [False False]
  [False False]]

 [[ True  True]
  [ True  True]
  [ True  True]]

 [[ True  True]
  [ True  True]
  [ True  True]]]
[ 6  7  8  9 10 11 12 13 14 15 16 17]
17
0


In [24]:
# Array manipulation
a = np.arange(9).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [25]:
ravelled_array = a.ravel()
#ravelled_array[2] = 4564
print(ravelled_array)
print(a)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [26]:
flattened_array = a.flatten()
flattened_array[2] = 1000000
print(flattened_array)
print(a)

[      0       1 1000000       3       4       5       6       7       8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [27]:
"""
* Flatten -> always return a copy and allocates new memory, changes to flatten will not reflect to orig array
* Ravel -> returns a view of the array, changes to ravel will reflect to original
"""

'\n* Flatten -> always return a copy and allocates new memory, changes to flatten will not reflect to orig array\n* Ravel -> returns a view of the array, changes to ravel will reflect to original\n'

In [28]:
y = np.arange(10).reshape(2, 5)
print(y)
print(y.transpose())
print(y.T) # short form of transpose()

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [29]:
# Resizing
y_resize = np.resize(y, (6, 6))
print(y_resize)

[[0 1 2 3 4 5]
 [6 7 8 9 0 1]
 [2 3 4 5 6 7]
 [8 9 0 1 2 3]
 [4 5 6 7 8 9]
 [0 1 2 3 4 5]]


In [30]:
print(np.zeros((3, 3), dtype=int))
print(np.ones((3, 3), dtype=int))
print(np.eye(3, 3))
print(np.random.rand(3, 3))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.7810784  0.80653002 0.11522366]
 [0.60517195 0.7154313  0.49837217]
 [0.16870697 0.10495117 0.58889311]]


In [32]:
# Matrix multiplication - 09282020
mat_a = np.matrix([0, 1, 2, 3, 4, 5]).reshape(2, 3) # initialize matrix with reshape(row, col)
mat_b = np.matrix([3, 4, 3, -2, 4, -2]).reshape(3, 2)
print(mat_a)
print(mat_b)

[[0 1 2]
 [3 4 5]]
[[ 3  4]
 [ 3 -2]
 [ 4 -2]]


In [34]:
product = np.matmul(mat_a, mat_b)
product

matrix([[11, -6],
        [41, -6]])

In [83]:
#Stacking
x = np.arange(4).reshape(2, 2)
y = np.arange(8).reshape(2, 4)
z = np.arange(4).reshape(2, 2)

print(x)
print(y)
print(z)

print("X shape: " + str(x.shape))

[[0 1]
 [2 3]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [2 3]]
X shape: (2, 2)


In [84]:
# h_stack = horizontal stacking n arrays into 1,
# both arrays musth have the same shape along the first axis 
# (vertically runs downward along the rows)
h_stack = np.hstack((x, y))
print(h_stack)
print("Stack shape: " + str(h_stack.shape))

[[0 1 0 1 2 3]
 [2 3 4 5 6 7]]
Stack shape: (2, 6)


In [85]:
# v_stack = vertically stacking n arrays into 1,
# both arrays musth have the same shape along the second axis 
# (vertically runs downward along the cols)
v_stack = np.vstack((x, z))
print(v_stack)
print("Stack shape: " + str(v_stack.shape))

[[0 1]
 [2 3]
 [0 1]
 [2 3]]
Stack shape: (4, 2)


In [86]:
#Concatenation of arrays
w = np.concatenate((x, y), axis=1) # concatenate at second axis
print(w)
v = np.concatenate((x, z), axis=0) # concatenate at first axis
print(v)

[[0 1 0 1 2 3]
 [2 3 4 5 6 7]]
[[0 1]
 [2 3]
 [0 1]
 [2 3]]


In [87]:
# Compare stack and concatenated arrays
print(h_stack == w)
print(v_stack == v)

[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]


In [90]:
# Depth stacking
# both arrays must be in same dimension, will add one dimension (3rd) 
depth_stack = np.dstack((x, z))
print(depth_stack)
print(depth_stack.shape) # n floors, n rows, n col

[[[0 0]
  [1 1]]

 [[2 2]
  [3 3]]]
(2, 2, 2)


In [94]:
# Column stacking
# Stack both arrays along second axis (cols)
col_stack = np.column_stack((x, y))

print(x.shape)
print(y.shape)
print(col_stack)
print(col_stack.shape)

(2, 2)
(2, 4)
[[0 1 0 1 2 3]
 [2 3 4 5 6 7]]
(2, 6)


In [97]:
# Column stacking
# Stack both arrays along first axis (rows)
row_stack = np.row_stack((x, z))

print(x.shape)
print(z.shape)
print(row_stack)
print(row_stack.shape)

(2, 2)
(2, 2)
[[0 1]
 [2 3]
 [0 1]
 [2 3]]
(4, 2)
