In [3]:
# How to create Numpy arrays
import numpy as np

# Simplest is to create arrays of ones and zeros
x = np.ones((2, 4)) # r, c
y = np.zeros((2,5))

print(x)
print(y)

# creating an array from a Python sequence
a = np.array([i ** 2 for i in range(2, 10)])

# array of evenly-spaced points
a = np.linspace(0,10,5)
a

# creating an array by sampling 10 numbers
# randomly from a mean-1, std-dev-5 normal
# distribution
c = np.random.normal(1, 5, 10)
print(c)
# creating an array of a specified datatype
np.array([1.5, 3.20, 5.78], dtype=int)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[ 0.17186254 -4.97116159  3.37780523  2.70825262  6.43118828  1.6260429
  2.59378651 -9.16579527 -0.42719168  6.01766225]


array([1, 3, 5])

In [21]:
# arange and linspace
a = np.arange(1, 20, 1) # start (included): 0, stop (excluded): 10, step:1
print(a)

# supplying one value to `arange` amounts to specifying the stop value
a = np.arange(10)
a

'''
 The linspace function allows you to generate  evenly-spaced points within a user-specified interval  
 ( and  are included in the interval). This is often used to generate a domain of values on which to evaluate 
 a mathematical function (e.g. if you want to the sine function from  to  on a finely-divided grid).
'''

# generate five evenly-spaced points on the interval [-1, 1]
a = np.linspace(-1, 1, 5)
a

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([-1. , -0.5,  0. ,  0.5,  1. ])

In [30]:
# Random sampling method
rng = np.random.default_rng()
# print(rng)

# create a shape-(3,3) array by drawing its entries randomly
# from the uniform distribution [0, 1)
x = rng.random((3,5))
print(x)

# create a shape-(5,) array by drawing its entries randomly
# from a mean-0, variance-1 normal (a.k.a. Gaussian) distribution
rng.normal(size=(5,))

[[0.1931372  0.09002433 0.47890536 0.93592139 0.09669184]
 [0.95658612 0.87122978 0.56070687 0.92521851 0.81157169]
 [0.21963757 0.2870891  0.27358881 0.84784779 0.65992942]]


array([ 1.37360749,  0.04796838,  0.29831944, -0.62404966, -0.60609167])

In [43]:
# Joining arrays together
x = np.linspace(-1, 1, 5)
print(x)
# y = np.ones((1, 5))
y = np.linspace(-1, 2, 5)
print(y)

# Stacking methods - stack 'x' and 'y' vertically
a = np.vstack([x, y])
print(a)
# Stacking methods - stack 'x' and 'y' horizontally
b = np.hstack([x, y])
print(b)

[-1.  -0.5  0.   0.5  1. ]
[-1.   -0.25  0.5   1.25  2.  ]
[[-1.   -0.5   0.    0.5   1.  ]
 [-1.   -0.25  0.5   1.25  2.  ]]
[-1.   -0.5   0.    0.5   1.   -1.   -0.25  0.5   1.25  2.  ]


In [8]:
# Array iteration
# First try with 'enumerate' function in an iterable
[i for i in enumerate('abcdef')]

# try enumerate in an array
x = np.array([i ** 2 for i in range(2, 5)])
print(x)
print([i for i in enumerate(x)]) # works, putting array in enumerate

[ 4  9 16]
[(0, 4), (1, 9), (2, 16)]


In [18]:
# Using numpy ndenumerate
x = np.array([[[90, 23, 3], 
               [23, 45, 44]], 
              [[-8, 23, 43], 
               [1, 3, 4]]])

[i for i in np.ndenumerate(x)] # enumerating through 3 d array

print(x[1, 1, 2])

4


In [24]:
'''
2 types of array traversal method in Numpy -> row-major (c) VS column-major (F) traversal ordering
Numpy utilizes row-major ordering as a default for any operation that requires an array to be traversed
'''

x = np.arange(2*3*4) # it will be an 1-d array
x.reshape(2,3,4)
x.reshape(4,6)

# Testing
# np.arange(10).reshape(2,5).reshape(10)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])