In [7]:
import numpy as np

In [8]:
# Basic declaration of array numpy
x = np.array([[0., 1., 2.],
              [3., 4., 5.],
              [6., 7., 8.]])

x

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [11]:
# Begin simple operations
x = x ** 2

print(x)

# Square root of each entry in array
x = np.sqrt(x)
print(x)

# Slices return arrays, operate on these too.
# Add 0.5 to row 0 of x
y = .5 + x[0, :]
y

[[ 0.  1.  4.]
 [ 9. 16. 25.]
 [36. 49. 64.]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


array([0.5, 1.5, 2.5])

In [34]:
# Operation between two arrays
x = np.array([[0., 1., 2.],
              [3., 4., 5.],
              [6., 7., 8.]])

y = np.array([[-4, -3.5, -3.,], 
              [-2.5, 2, 1.5], 
              [-1, -0.5, -0.]])

print(x + y)

print(x * y)

# Operations on sequence of numbers (sum)
print(np.sum(x))

# Summing over rows (axis = 0)
print(np.sum(x, axis=0)) # rows
print(np.sum(x, axis=1)) # columns

[[-4.  -2.5 -1. ]
 [ 0.5  6.   6.5]
 [ 5.   6.5  8. ]]
[[-0.  -3.5 -6. ]
 [-7.5  8.   7.5]
 [-6.  -3.5 -0. ]]
36.0
[ 9. 12. 15.]
[ 3. 12. 21.]


In [25]:
'''
Vectorized Operations

Vectorization - the use of optimized, pre-compiled code written in a low-level language (e.g. C) 
                to perform mathematical operations over a data sequence. This is done in in place
                of an explicit iteration written in the native language
Vectorization outcome can be a tremendous speedup relative to analogous computation performed in Python.
'''
import time

# exp pof numpy
start = time.time()
print(np.sum(np.arange(10000))) # Using sum reduce the computing time (~11 microseconds)
end = time.time()

total_time = end - start
print("\nTotal time: "
      + str(total_time) + 's')

# Similar output, but different methods which takes a lot more computing time
total = 0
start = time.time()
for i in np.arange(10000):
    total += i
print(total)
end = time.time()
print("\nTotal time: "
      + str(total_time) + 's')

print(2 * np.array([2, 3, 4]))

print(np.array([11, 12]) - np.array([10, 124]))
# dot = multiply their corresponding entries and sum result
print(np.dot(np.array([1, -3, 4]), np.array([2, 0, 12])))

49995000

Total time: 0.0009992122650146484s
49995000

Total time: 0.0009992122650146484s
[4 6 8]
[   1 -112]
50


In [44]:
'''
Numpy Unary functions
'''
x = [1., 2., 3.]
y = np.exp(x)
y

# Performing unary functions on 2D-array
x = np.array([[-1, 2], [3, 4]])
x
print(np.log10(x))

[[       nan 0.30103   ]
 [0.47712125 0.60205999]]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in log10
  # This is added back by InteractiveShellApp.init_path()


In [52]:
# Test - apply log to 2-D array of 
x = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11],
              [12, 13, 14, 15]])

print(np.log(x[2, 0::2]))

y = np.array([[np.log(x[2,0])],
              [np.log(x[2,2])]
             ])
y

[2.07944154 2.30258509]


array([[2.07944154],
       [2.30258509]])

In [54]:
np.maximum(2, 444)
np.minimum(11, 4)

4