In [2]:
# Mathematical functions of Numpy
'''
Official documentation: https://numpy.org/doc/stable/reference/ufuncs.html#math-operations
'''

# Numpy Array Broadcasting
'''
Apply binary NumPy functions to arrays of unlike shapes. 
Exp: adding a single-shape(2,) array with ten of such arrays, which are stored as a single shape-(10,2) array
'''

import numpy as np

x = np.array([[10, 2],
              [3,  5]])

y = np.array([[11, 3], 
              [23, 45]])

np.add(x, y)

# add column 0 of x with row-1 of y
np.add(x[:, 1], y[0, :])

# add row-1 of y with column 0 of x
# np.add(y[1, :], x[:, 0])

# Exp: binary functions of NumPy array
x = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11],
              [12, 13, 14, 15]])

print(x[:2, :2])
print(x[-2:,:2])
print(x[:2, -2:])

# top-left  top-right    bottom-left  bottom-right
x[:2, :2] + x[:2, -2:] + x[-2:, :2] + x[-2:, -2:]

[[0 1]
 [4 5]]
[[ 8  9]
 [12 13]]
[[2 3]
 [6 7]]


array([[20, 24],
       [36, 40]])

In [4]:
# Example of Unary functions of NumPy Math
# Log function
x = np.array([[0, 1, 2, 3],
             [4, 5, 6, 7],
             [8, 9, 10, 11],
             [12, 13, 14, 15]])

np.log(x[2, 0:2])

array([2.07944154, 2.19722458])

In [11]:
# Binary functions
# Continue 4/11/2022 (evening)

x = np.array([0., 1., 2.])
y = np.array([0., 1., 2.])

print(x)
print(y)

np.multiply(x,y)

[0. 1. 2.]
[0. 1. 2.]


array([0., 1., 4.])

In [19]:
# Add 4 quadrants of x into a shape(2, 2) output
x = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11],
              [12, 13, 14, 15]])

# print(x[:2, :2])
# print(x[-2:,:2])
# print(x[:2, -2:])
# print(x[-2:, -2:]

y = x[:2, :2] + x[-2:,:2] + x[:2, -2:] + x[-2:, -2:]  
print(y)

[[20 24]
 [36 40]]


In [13]:
# Array generalization of any dimensonality and shape

# Sequentia functions of NumPy
x = np.array([1, 2, 5])
x

print(x.sum())

print(np.round(x.mean()))

# sequential functions of n-dimensional array
x = np.array([[0, 1], [2, 3], [3, 5]])
print(x.sum()) # same as invoke np.sum(x)
print(np.sum(x))

'''
This default behavior of sequential NumPy functions can be overwritten by specifying the keyword argument 
axis within the sequential function. This is a very useful and common thing to do. We will carefully study 
what the axis argument is used for in these and other NumPy functions.
'''

8
3.0
14
14


'\nThis default behavior of sequential NumPy functions can be overwritten by specifying the keyword argument \naxis within the sequential function. This is a very useful and common thing to do. We will carefully study \nwhat the axis argument is used for in these and other NumPy functions.\n'

In [3]:
# Specifying the axis keyword in sequential NumPy functions
# creating a 3-d array

x = np.array([[1, 3], [1, 4], [2,5]])

'''
The axis argument thus specifies which axis or axes are traversed to produce the input sequences 
for the sequential function to act on. One sequence is designated for each valid combination of 
indices of the non-traversed axes. For example, np.sum(x, axis=0) 
says: “for each of the columns of x, sum over its rows”. 
'''

print(np.sum(x)) # same as sum over axis=(0,1)
# sum over axis-0, within axis-1
print(np.sum(x, axis=0))
# sum over axis-1, within axis-0
print(np.sum(x, axis=1))
# sum over axis 0 and axis 1
print(np.sum(x, axis=(0,1)))

x.sum(axis=0) # same as np.sum(x, axis=0), pretty useful

16
[ 4 12]
[4 5 7]
16


array([ 4, 12])

In [23]:
'''
How to use axis-argument within a multi-dimensional array
'''
# x = np.arange(24)
# print(x)
# x.reshape(4,2,3)

# Can also be written as below
x = np.arange(24).reshape(4, 2, 3)
print(x)
# print(x[:, 0, 0]) # note, : means every option, in this case dimension (array)

# print(np.mean(x))
np.mean(x, axis=0)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


array([[ 9., 10., 11.],
       [12., 13., 14.]])

In [5]:
# Array Generalization
x = np.array([[10, 2], [12, 3]])
x = np.maximum(4., x)
x

array([[10.,  4.],
       [12.,  4.]])

In [13]:
# Sequential functions
'''
mean, median, var, max, standard deviation, argmax, etc..
'''
# Dealing with vector (1-d array)
x = np.array([0., 2., 4.])
print(np.mean(x))

2.0


In [47]:
# Sequential functions practice - https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/VectorizedOperations.html
# Examples - computation of sequential functions

images = np.random.rand(100, 32, 32, 3)
images

# Compute following:
# 1. Average 32 x 32 RGB image
# print(images.mean(axis=0)) # can also be written as
avg = np.mean(images, axis=(0)) # Correct
avg.shape

# 2. Total sum of all values in the array
# total_sum = np.sum(images, axis=(0)) # wrong
total_sum = np.sum(images)
# print(total_sum)
# total_sum.shape

# 3. Minimum blue value, respective to each image
min_blue = images[:, :, :, 2].min(axis=(1, 2))
min_blue
# min_blue.shape -- (100, )

# 4. The standard deviation among all the RGB values in all the images, respective to each pixel position 
# (thus you should produce a shape-(32, 32) array of values).
std = np.std(images, axis=(0, 3))
std
# std.shape

# Maximum red value in top left quadrant, respective to each image
max_red_quad = images[:, :16, :16, 0].max(axis=(1,2))
max_red_quad
# max_red_quad.shape -- (100, )

(100,)