In [3]:
# Mathematical functions of Numpy
'''
Official documentation: https://numpy.org/doc/stable/reference/ufuncs.html#math-operations
'''

# Numpy Array Broadcasting
'''
Apply binary NumPy functions to arrays of unlike shapes. 
Exp: adding a single-shape(2,) array with ten of such arrays, which are stored as a single shape-(10,2) array
'''

import numpy as np

x = np.array([[10, 2],
              [3,  5]])

y = np.array([[11, 3], 
              [23, 45]])

np.add(x, y)

# add column 0 of x with row-1 of y
np.add(x[:, 1], y[0, :])

# add row-1 of y with column 0 of x
# np.add(y[1, :], x[:, 0])

# Exp: binary functions of NumPy array
x = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11],
              [12, 13, 14, 15]])

print(x[:2, :2])
print(x[-2:,:2])
print(x[:2, -2:])

# top-left  top-right    bottom-left  bottom-right
x[:2, :2] + x[:2, -2:] + x[-2:, :2] + x[-2:, -2:]

[[0 1]
 [4 5]]
[[ 8  9]
 [12 13]]
[[2 3]
 [6 7]]


array([[20, 24],
       [36, 40]])

In [4]:
# Example of Unary functions of NumPy Math
# Log function
x = np.array([[0, 1, 2, 3],
             [4, 5, 6, 7],
             [8, 9, 10, 11],
             [12, 13, 14, 15]])

np.log(x[2, 0:2])

array([2.07944154, 2.19722458])

In [11]:
# Binary functions
# Continue 4/11/2022 (evening)

x = np.array([0., 1., 2.])
y = np.array([0., 1., 2.])

print(x)
print(y)

np.multiply(x,y)

[0. 1. 2.]
[0. 1. 2.]


array([0., 1., 4.])

In [19]:
# Add 4 quadrants of x into a shape(2, 2) output
x = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11],
              [12, 13, 14, 15]])

# print(x[:2, :2])
# print(x[-2:,:2])
# print(x[:2, -2:])
# print(x[-2:, -2:]

y = x[:2, :2] + x[-2:,:2] + x[:2, -2:] + x[-2:, -2:]  
print(y)

[[20 24]
 [36 40]]


In [ ]:
# Array generalization of any dimensonality and shape
# Continue on - http://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/VectorizedOperations.html#NumPy%E2%80%99s-Mathematical-Functions