In [1]:
import numpy as np

In [25]:
# Basic declaration of array numpy
x = np.array([[0., 1., 2.],
              [3., 4., 5.],
              [6., 7., 8.]])

x

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [27]:
# Begin simple operations
x = x ** 2

print(x)

# Square root of each entry in array
x = np.sqrt(x)
print(x)

# Slices return arrays, operate on these too.
# Add 0.5 to row 0 of x
x = .5 + x[0, :]
x

[0.25 2.25 6.25]
[0.5 1.5 2.5]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [34]:
# Operation between two arrays
x = np.array([[0., 1., 2.],
              [3., 4., 5.],
              [6., 7., 8.]])

y = np.array([[-4, -3.5, -3.,], 
              [-2.5, 2, 1.5], 
              [-1, -0.5, -0.]])

print(x + y)

print(x * y)

# Operations on sequence of numbers (sum)
print(np.sum(x))

# Summing over rows (axis = 0)
print(np.sum(x, axis=0)) # rows
print(np.sum(x, axis=1)) # columns

[[-4.  -2.5 -1. ]
 [ 0.5  6.   6.5]
 [ 5.   6.5  8. ]]
[[-0.  -3.5 -6. ]
 [-7.5  8.   7.5]
 [-6.  -3.5 -0. ]]
36.0
[ 9. 12. 15.]
[ 3. 12. 21.]


In [10]:
'''
Vectorized Operations

Vectorization - the use of optimized, pre-compiled code written in a low-level language (e.g. C) 
                to perform mathematical operations over a data sequence. This is done in in place
                of an explicit iteration written in the native language
Vectorization outcome can be a tremendous speedup relative to analogous computation performed in Python.
'''
# exp pof numpy
print(np.sum(np.arange(10000))) # Using sum reduce the computing time (~11 microseconds)

# Similar output, but different methods which takes a lot more computing time
total = 0
for i in np.arange(10000):
    total += i
print(total)

print(2 * np.array([2, 3, 4]))

print(np.array([11, 12]) - np.array([10, 124]))
# dot = multiply their corresponding entries and sum result
print(np.dot(np.array([1, -3, 4]), np.array([2, 0, 12])))

49995000
49995000
[4 6 8]
[   1 -112]
50


In [18]:
# Mathematical functions of Numpy
'''
Official documentation: https://numpy.org/doc/stable/reference/ufuncs.html#math-operations
'''

# Numpy Array Broadcasting
'''
Apply binary NumPy functions to arrays of unlike shapes. 
Exp: adding a single-shape(2,) array with ten of such arrays, which are stored as a single shape-(10,2) array
'''

x = np.array([[10, 2],
              [3,  5]])

y = np.array([[11, 3], 
              [23, 45]])

np.add(x, y)

# add column 0 of x with row-1 of y
np.add(x[:, 1], y[0, :])

# add row-1 of y with column 0 of x
# np.add(y[1, :], x[:, 0])

array([13,  8])

In [31]:
# Exp: binary functions of NumPy array
x = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11],
              [12, 13, 14, 15]])

print(x[:2, :2])
print(x[-2:,:2])
print(x[:2, -2:])

# top-left  top-right    bottom-left  bottom-right
x[:2, :2] + x[:2, -2:] + x[-2:, :2] + x[-2:, -2:]

[[0 1]
 [4 5]]
[[ 8  9]
 [12 13]]
[[2 3]
 [6 7]]


array([[20, 24],
       [36, 40]])