In [2]:
# Basic immports
import numpy as np

x = np.array([0, 1, 2, 3, 4, 5])
print(x)

type(x)

[0 1 2 3 4 5]


numpy.ndarray

In [13]:
# reshaping array n row, i columns
x = x.reshape(2, 3)

print(x)

x = x.reshape(3, 2)
print(x)

x = x**2
x

x = np.power(x, 2)
x

# calculate mean value along the three distinct rows of our data
np.mean(x, axis=1)

[[          0           1           0]
 [-1970898431           0   781532673]]
[[          0           1]
 [          0 -1970898431]
 [          0   781532673]]


array([ 5.00000000e-01,  9.97782528e+08, -2.99837435e+07])

In [18]:
# use broadcasting to rais each column of x to a different power
y = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
y = y.reshape(3,3)
y ** np.array([0., 1., 2.])

# Array indexing
# access 2nd and 3rd columns
y[:2, :3]

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
#  Accessing N-dimensional array

# Example of 3D-array
x = np.array([[[0,1], [2,3]], [[4,5], [6,7]]])
# get: sheet-0, both rows, flip order 
x[0, :, ::-1]

array([[1, 0],
       [3, 2]])

In [32]:
# Two-dimensional arrays
grades = np.array([[93, 94],[98, 99], [83, 74]])
grades

grades.shape

# 2D-array indexing
# row 0, col 1
print(grades[0, 1])
# using -ve indices
grades[-1, 0]
# Accessing multiple elements
print(grades[0:3, 1])
grades[0:3, 0]

94
[94 99 74]


array([93, 98, 83])

In [37]:
# 3-D array
three_d_array = [[[23, 23], 
                  [47,23]], 
                 [[456, 56], 
                  [34, 65]
                ]]

print(three_d_array)

# Using NumPy array
three_d_array = np.array([[[23, 23], 
                           [47,23]], 
                          [[456, 56], 
                           [34, 65]]])

print(three_d_array)

# Retrieving a single element from a 3D-array
three_d_array[0, 1, 0] # first dimension, row 1, col 0
three_d_array[:, 0, 0] # specify elements in row-0 and column-0 of both sheets
three_d_array[1]

[[[23, 23], [47, 23]], [[456, 56], [34, 65]]]
[[[ 23  23]
  [ 47  23]]

 [[456  56]
  [ 34  65]]]


array([[456,  56],
       [ 34,  65]])

In [46]:
# Multi-dimensional indexing
arr = np.array([[[ 0,  1,  2],
                 [ 3,  4,  5],
                 [ 6,  7,  8]],

                [[ 9, 10, 11],
                 [12, 13, 14],
                 [15, 16, 17]],

                [[18, 19, 20],
                 [21, 22, 23],
                 [24, 25, 26]]])

# transpose array
# print(arr[0].shape)
trans_one = arr[0].T
# print(trans_one)

# Indexing
# a
print(arr[:, :, 2])
# b
print(arr[0:2, 1, :])
# c
print(arr[0, 0:2, 2])
# d
# print(arr[1, 0:3, :])
# print(arr[1, :, :]) # more simp0ified way
print(np.fliplr(arr[1,:,:])) # URL: https://www.geeksforgeeks.org/how-to-reverse-column-order-in-a-matrix-with-python/
# Reference anser
print(arr[1, :, ::-1])

[[ 2  5  8]
 [11 14 17]
 [20 23 26]]
[[ 3  4  5]
 [12 13 14]]
[2 5]
[[11 10  9]
 [14 13 12]
 [17 16 15]]
[[11 10  9]
 [14 13 12]
 [17 16 15]]


In [1]:
# Zero dimensional arrays
x = np.array(15.2)

x
# can only use arr.item() to access 0-d array
x.item()
# Error
x[0]

NameError: name 'np' is not defined

In [47]:
# Array manipulations
x = np.array([[1, 2, 3, 4], [5,6,7,8]])
x.shape
# Reshape
'''Prerequisites: the size the the initial array must match the size of the to-be reshaped array:'''
y = x.reshape(4,2)
# Multi-dimension array
x = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [9, 11, 12, 13]])
print(x.reshape(3, 2, 2))

# Flatten array
flat = y.flatten('K')
flat

# Auto arrange array?
a = np.arange(36) # assigning an array of values 0 to 35, n = size limit
# Valid reshaping
print(a.reshape(3, 4, 3)) # Remember shape must match the size of array
# print(a.reshape(3, 4, 2)) # wrong example
# print(a.reshape(2, 6, 3))
print(a.reshape(3, 4, -1)) # NumPy replaces -1 with 36/(3*4) -> 3
# Using -1 to specify only one dimension
print(a.reshape(3, 1, -1)) # not valid
# print(a.reshape(3, -1, -1)) # not valid
# Transpose

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 9 11]
  [12 13]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]
[[[ 0  1  2  3  4  5  6  7  8  9 10 11]]

 [[12 13 14 15 16 17 18 19 20 21 22 23]]

 [[24 25 26 27 28 29 30 31 32 33 34 35]]]


In [54]:
# Basic Array attributes
# check number of axes (dimensions) of array
exp = np.array([[[ 0,  1,  2,  3.123],
                 [ 4,  5,  6,  7]],
                  [[ 8,  9, 10, 11],
                   [12, 13, 14, 15]],
                  [[16, 17, 18, 19],
                   [20, 21, 22, 23]]])

print(exp.ndim)
# shape of array
print(exp.shape) # sheets, row, col
# size
print(exp.size)

# Special attr
# data type
print(exp.dtype) # seems can detect the distinct datatype which are 
                 # different from the most, if there's a float among int, array attrbutes will change
# item size (in bytes)
print(exp.itemsize)



3
(3, 2, 4)
24
float64
8
