In [1]:
# Basics of File I/O
from pathlib import Path
root = Path(".")

root

WindowsPath('.')

In [11]:
# Creating a path to subsequent directory
path_to_data1 = root / "data"/ "data1.txt"
path_to_data1

# Check if file / directory exists
print(path_to_data1.exists())
print(root.exists())

# Absolute path
print(path_to_data1.absolute())

# Access the name of the file that the path is point
path_to_data1.name

# Create a new directory, named 'new_folder' within the root directory
new_dir = root / "files"

if(not(new_dir.exists())):
    new_dir.mkdir() # make directory

str(path_to_data1)

False
True
C:\Users\setsu\Documents\Projects\Python_Learning\Machine Learning\Crash Courses\data\data1.txt


'data\\data1.txt'

In [12]:
"""
Opening Files

Official tutorial - https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files

Mode for file I/O:
'r'
'w'
'a'
'x'
'+'
"""
path_to_file = Path("files/file1.txt")
with open(path_to_file, mode="a") as f:
    # The indented space enters the "context" of the open file.
    # Leaving the indented space exits the context of the opened file, forcing
    # the file to be closed. This is ensured even if the code within the indented
    # block causes an error.
    f.write('\nthis is a line.\nThis is a second line.\nThis is the third line.')

# File closes here

In [44]:
# Extra - saving a NumPy-array to file
'''
You can instead force Python to read and write strictly in terms of binary data by adding a 'b' 
to these modes: 'rb', 'wb', 'ab', 'xb', '+b'. It is important to be aware of this binary mode. 
For example, if you are saving a NumPy-array, you should open a file in the ‘wb’ or ‘xb’ modes 
so that it expects binary data to be written to it; obviously we are not saving text 
when we are saving a NumPy array of numbers.
'''
import numpy as np

x = np.array([1, 2, 3])

with open("array.npy", mode="wb") as f:
    np.save(f, x)

In [13]:
# File reading
with open(path_to_file, mode="r") as f:
    content = f.read()
#     print(content)

print(content)


this is a line.
This is a second line.
This is the third line.


In [14]:
# Exercise
# Write string to a file in the present directory
some_text = """A bogel rolled down the hill.
I mean *all* the way down the hill.
A lady watched it roll.
Way to help me out."""

some_text

with open('files/a_poem.txt', mode='x') as f:
    f.write(some_text)

In [20]:
with open('files/a_poem.txt', mode='r') as open_file:
#     out = [line for line in open_file]
    out = [line for line in open_file if line.startswith('A')]

out

['A bogel rolled down the hill.\n', 'A lady watched it roll.\n']

In [43]:
# File globbing
'''
A glob is a set of file names matching some pattern. To glob files, we use special wildcard characters that will match all the files
with a certain part of a file name. It matches any character.
'''
root_dir = Path('./files')
print(root_dir)


# Create a new file named '*quirk.txt'
path_quirk = Path("files/a_quirk.txt")

with open(path_quirk, mode="w") as f:    
    f.write('\nthis is a line.\nThis is a second line.\nThis is the third line.')

files = root_dir.glob('*.txt')

sorted(files)
quirk_files = root_dir.glob('*quirk.txt')
sorted(quirk_files)

data_files = root_dir.glob('data*.txt')
sorted(data_files)

q_w_files = root_dir.glob('q*w*.npy')
sorted(q_w_files)

files


[]

In [44]:
# Using square brackes in globing - [abc]* or [0-9]*

# Comprehension. Write a glob pattern that matches below example:
# any file with an odd number in its name
# Answ: *[13579]*
# all txt files that have the letters 'q' or 'z' in them
# Ans: *[qz]*

In [45]:
# Saving and Loading pyhon objects: pickle
import pickle

grades = {
    'Albert': 92,
    'David': 54,
    'Emmy': 98,
    "Marie": 56
}

#  save objects pickle.dump
with open('grades.pkl', mode="wb") as file:
    pickle.dump(grades, file)

# load objects pickle.load
with open('grades.pkl', mode="rb") as f:
    loaded_grades = pickle.load(f)

loaded_grades

{'Albert': 92, 'David': 54, 'Emmy': 98, 'Marie': 56}

In [46]:
# Saving and loading numpy arrays
import numpy as np
x = np.array([1, 2, 4])
np.save('x.npy', x)

y = np.load('x.npy')

y

array([1, 2, 4])

In [42]:
# save three arrays to a numpy archive file
a0 = np.array([1, 2, 3])
a1 = np.array([4, 5, 6])
a2 = np.array([7, 8, 9])

# we provide the keywords arguments `soil`, `crust`, and `bedrock`,
# as the names of the respective arrays in the archive.
np.savez("my_archive.npz", soil=a0, crust=a1, bedrock=a2)

# opening the archive and accessing each array by name
with np.load("my_archive.npz") as my_archive_file:
    out0 = my_archive_file["soil"]
    out1 = my_archive_file["crust"]
    out2 = my_archive_file["bedrock"]
    
print(out0)
print(out1)
print(out2)

[1 2 3]
[4 5 6]
[7 8 9]
