In [2]:
import numpy as np

In [25]:
# Basic declaration of array numpy
x = np.array([[0., 1., 2.],
              [3., 4., 5.],
              [6., 7., 8.]])

x

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [27]:
# Begin simple operations
x = x ** 2

print(x)

# Square root of each entry in array
x = np.sqrt(x)
print(x)

# Slices return arrays, operate on these too.
# Add 0.5 to row 0 of x
x = .5 + x[0, :]
x

[0.25 2.25 6.25]
[0.5 1.5 2.5]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [34]:
# Operation between two arrays
x = np.array([[0., 1., 2.],
              [3., 4., 5.],
              [6., 7., 8.]])

y = np.array([[-4, -3.5, -3.,], 
              [-2.5, 2, 1.5], 
              [-1, -0.5, -0.]])

print(x + y)

print(x * y)

# Operations on sequence of numbers (sum)
print(np.sum(x))

# Summing over rows (axis = 0)
print(np.sum(x, axis=0)) # rows
print(np.sum(x, axis=1)) # columns

[[-4.  -2.5 -1. ]
 [ 0.5  6.   6.5]
 [ 5.   6.5  8. ]]
[[-0.  -3.5 -6. ]
 [-7.5  8.   7.5]
 [-6.  -3.5 -0. ]]
36.0
[ 9. 12. 15.]
[ 3. 12. 21.]


In [35]:
'''
Vectorized Operations

Vectorization - the use of optimized, pre-compiled code written in a low-level language (e.g. C) 
                to perform mathematical operations over a data sequence. This is done in in place
                of an explicit iteration written in the native language
Vectorization outcome can be a tremendous speedup relative to analogous computation performed in Python.
'''
# exp pof numpy
np.sum(np.arange(10000)) # Continue

49995000